# Main script

## imports, deleting possible dupes and printing data

In [1]:
import pandas as pd
import numpy as np
import time
from datetime import datetime, date, time, timedelta

In [2]:
data = pd.read_csv("../Original Data/billboard.csv")
data = data.drop_duplicates()
data

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2000,Ghostface Killah,Cherchez LaGhost,3:04,R&B,2000-08-05,2000-08-05,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Smith, Will",Freakin' It,3:58,Rap,2000-02-12,2000-02-12,99,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,99,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Processing
Selecting "year","artist", "track" and "time" from original data, adding "date","week" and "place" fields.

Each row will respresent a song every week with it's rank.

In [3]:
print(len(data))
songs = data.loc[:,['year','artist.inverted','track','time','genre']]
places = data.loc[:,'x1st.week':]

data_place_by_week = pd.DataFrame(columns = ["year","artist", "track","time","date","week","place"])
for d,r in data.iterrows():
    week = 0
    for w, place in places.loc[d,:].iteritems():
        
        if not np.isnan(place):
            date = datetime.strptime(r['date.entered'], '%Y-%m-%d') + timedelta(weeks = week)
            date = date.strftime("%Y-%m-%d")
            #print(date.strftime("%Y-%m-%d"),weeks+1,place)
            new_row = [r['year'],r['artist.inverted'],r['track'],r['time'],date ,week + 1,int(place)]
            #print(new_row)
            data_place_by_week.loc[len(data_place_by_week)]= new_row
        week+=1
        
    total_weeks = week

data_place_by_week.to_csv("../Analysis Data/analysisData_1.csv")

data_place_by_week

317

,year,artist,track,time,date,week,place
0,2000,Destiny's Child,Independent Women Part I,3:38,2000-09-23,1,78
1,2000,Destiny's Child,Independent Women Part I,3:38,2000-09-30,2,63
2,2000,Destiny's Child,Independent Women Part I,3:38,2000-10-07,3,49
3,2000,Destiny's Child,Independent Women Part I,3:38,2000-10-14,4,33
4,2000,Destiny's Child,Independent Women Part I,3:38,2000-10-21,5,23
...,...,...,...,...,...,...,...
5302,2000,Zombie Nation,Kernkraft 400,3:30,2000-09-02,1,99
5303,2000,Zombie Nation,Kernkraft 400,3:30,2000-09-09,2,99
5304,2000,"Eastsidaz, The",Got Beef,3:58,2000-07-01,1,99
5305,2000,"Eastsidaz, The",Got Beef,3:58,2000-07-08,2,99
5306,2000,Fragma,Toca's Miracle,3:22,2000-10-28,1,99